projects:
  app:
    schemaPath: server/generated/prisma.graphql
    extensions:
      endpoints:
        default: http://localhost:8080
  prisma:
    schemaPath: server/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml